### ISSUE TITLE
KoAT is inaccessible

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#55]
@nilslommen Please make KoAT accessible from me, e.g. by linking it in a public space.

**Comment by nilslommen** [comment]
This is strange. It should already be public since I have added the "public user". Can you access it [here](https://www.starexec.org/starexec/secure/details/solver.jsp?id=45388)?

**Comment by nilslommen** [comment]
Thanks for pointing it out. I thought it would be enough to add the "public" user but one still has to make the folder public. I hope it works now.

**Comment by AkihisaYamada** [comment]
Thanks, it works now :)
