### ISSUE TITLE
conflict in C Integer

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#56]
@nilslommen @juergengiesl @hiroshi-unno Please discuss!
https://termcomp.herokuapp.com/Y2023/C_Integer.html?filter1=c

**Comment by AkihisaYamada** [comment]
This is the last year's result:
https://termcomp.herokuapp.com/Y2022/C_Integer.html?filter0=Stroeder_15/LogMult.c

It's shown terminating by iRankfinder, which dropped out this year. AProVE wasn't really involved there.

**Comment by nilslommen** [comment]
This benchmark should be terminating as y grows strictly monotonically and hence becomes larger than x (which is not changed in the loop) at some point. So, this seems to be a bug by last year's iRankFinder configuration (with non-linear arithmetic).

**Comment by AkihisaYamada** [comment]
Thank you for the analysis! Then C Integer has no conflict now
