### ISSUE TITLE
Ultimate not working?

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#59]
@Heizmann could you check if ultimate is working?

https://termcomp.herokuapp.com/Y2023/C.html

I suspect the JRE must be combined into the uploaded zip.

**Comment by Heizmann** [comment]
Thanks for the hint.
My test run did not finish before the deadline and I forgot to look at the results afterwards.
The new version that I uploaded succeeded in my tests. You merged the pull request already. Thanks!

**Comment by AkihisaYamada** [comment]
Thanks for the fix, in my private run I observe it running right.
