### ISSUE TITLE
conflicts in ITS

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#60]
http://termcomp.herokuapp.com/Y2023/Integer_Transition_Systems.html?filter1=c

@hiroshi-unno it seems at least one config of MuVal is buggy. Please check :)

**Comment by hiroshi-unno** [comment]
@AkihisaYamada Thank you for letting me know. It seems that the preprocessing I implemented just before the deadline had a bug. I've made the corrections and sent a pull request. I believe the latest version resolves the conflicts.

**Comment by AkihisaYamada** [comment]
I started a rerun: https://termcomp.herokuapp.com/job.php?id=60798&refresh=1

**Comment by AkihisaYamada** [comment]
I'll close it as I see no conflict in the test run and we got no comments.
