### ISSUE TITLE
KoAT & MuVal vs. LoAT conflict

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#61]
https://termcomp.herokuapp.com/Y2023/Integer_Transition_Systems.html?filter1=c

@ffrohn @nilslommen @hiroshi-unno There is one case where KoAT and MuVal agree but LoAT doesn't. Analysis please!

**Comment by nilslommen** [comment]
This benchmark should be non-terminating. We fixed KoAT in https://github.com/TermCOMP/starexec-master/pull/64.

**Comment by AkihisaYamada** [comment]
[This one](https://[termcomp.github.io/tpdb.html?ver=11.3&path=Integer_Transition_Systems%2FFrom_T2%2Fruslan-benchmarks_misc_n-38.t2.smt2](https://termcomp.github.io/tpdb.html?ver=11.3&path=Integer_Transition_Systems%2FFrom_T2%2Fruslan-benchmarks_misc_n-38.t2.smt2)): I don't know why it should be non-terminating or even what it is...

**Comment by ffrohn** [comment]
You mean [this one](https://termcomp.github.io/tpdb.html?ver=11.3&path=Integer_Transition_Systems%2FFrom_T2%2Fruslan-benchmarks_misc_n-38.t2.smt2), right? (The link in your post does not work.) @nilslommen and I had a look at it yesterday, we transformed it to something that is (more or less) human readable, and reconstructed the non-terminating run found by LoAT. Afterwards, @nilslommen identified the bug in KoAT that resulted in the wrong answer, so we're pretty sure that it is indeed non-terminating.

**Comment by AkihisaYamada** [comment]
OK thanks, check the rerun: https://termcomp.herokuapp.com/job.php?id=60738&refresh=1

**Comment by AkihisaYamada** [comment]
btw my link didn't work, because I pasted the url, which was smartly automatically transformed into a markdown link...

**Comment by AkihisaYamada** [comment]
Now MuVal fix is in. https://termcomp.herokuapp.com/job.php?id=60798&refresh=1

**Comment by AkihisaYamada** [comment]
I'll consider this issue is for KoAT and close it. It's interesting that the majority was wrong :)
