### ISSUE TITLE
NTI logic programming issue

### ISSUE THREAD

**Issue by etiennepayet** [TermCOMP/starexec-master#65]
For the following benchmarks,  NTI outputs 'MAYBE' instead of 'NO' because an exception is thrown (java.lang.UnsupportedOperationException):

Logic_Programming/BCGGV05/flat-fb.pl
Logic_Programming/BCGGV05/mergesort.pl
Logic_Programming/BCGGV05/permutation-fb.pl
Logic_Programming/BCGGV05/reverse-fb.pl
Logic_Programming/BCGGV05/slowsort-fb.pl	
Logic_Programming/lpexamples/mergesort-oi.pl
Logic_Programming/SGST06/transpose2.pl
Logic_Programming/talp_apt/quicksort-oi.pl
Logic_Programming/talp_talp/slowsort-oi.pl

During last year's competition, NTI was able to disprove termination of these benchmarks. There is something weird here, because I did not modify the code that finds a non-termination witness for them.

I just rebuilt the executable jar file, and the problem was solved...

**Comment by AkihisaYamada** [comment]
Thanks, please check the rerun and close the issue: https://termcomp.herokuapp.com/job.php?id=60760&refresh=1

**Comment by etiennepayet** [comment]
Problem magically solved by just rebuilding the executable jar file.
