### ISSUE TITLE
AProVE is unsound on variable lhs

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#69]
Pointed by @jwaldmann.

**Comment by AkihisaYamada** [comment]
@eleanoremeyer @nilslommen @juergengiesl Please check: https://termcomp.herokuapp.com/job.php?id=60792

@jwaldmann Interesting! It's maybe useful to include NO benchmarks if the strict rules alone are not NO.

**Comment by AkihisaYamada** [comment]
Let's say the issue is closed and continue the discussion at WST!

**Comment by juergengiesl** [comment]
Dear all,


>
>    1.
>
>    even if we keep some (easy) NO benchmarks around: if your solver has a
>    good nontermination checker, and it does not say NO after 10 seconds, then
>    you could print YES, with some random "proof" (chatgpt style plausible
>    nonsense) and have very little risk of conflict. I am not suggesting that
>    anyone does this on purpose ...
>
>
At the most recent SV-COMP 2023, the termination category was won by the
tool VeriFuzz which does exactly that. It can only prove non-termination
and if it does not succeed in proving non-termination, it gives the result
"yes", i.e., it is (sometimes) unsound for termination. I think that such
tools should only be permitted to give "no" answers, but no "yes" answers
at competitions.


>    1.
>
>    I was checking some proofs (AProVE for Waldmann-23) of the job you
>    linked. I was skeptical about
>    https://www.starexec.org/starexec/services/jobs/pairs/615205122/stdout/1?limit=-1
>    (for size-8-alpha-3-num-36.srs) because that is small matrices - why
>    matchbox does not find them? But it's fine: the given interpretation
>    *is* compatible with the left-context-closed system (that AProVE uses)
>    but not with the original system (that matchbox uses).
>
>
Yes, we also did not find any errors here.

Best Regards
Juergen
