### ISSUE TITLE
MuVal contradiction in C Integer

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#73]
@hiroshi-unno I still observe MuVal self conflict on
https://termcomp.github.io/tpdb.html?ver=11.3&path=C_Integer%2FStroeder_15%2FChawdharyCookGulwaniSagivYang-ESOP2008-aaron12_true-termination.c

This is skeptical MuVal NO job: https://www.starexec.org/starexec/secure/details/pair.jsp?id=615216726

MuVal RL YES: https://www.starexec.org/starexec/secure/details/pair.jsp?id=615216727

AProVE's YES: https://www.starexec.org/starexec/secure/details/pair.jsp?id=615216725

**Comment by AkihisaYamada** [comment]
@nilslommen @juergengiesl expert comments are welcome.
I guess a fix will not be feasible in-time so we need to be sure which is correct to apply 10-point deduction.

**Comment by hiroshi-unno** [comment]
@AkihisaYamada I've identified the cause of the bug, but it seems there might not be enough time before the deadline to fix it. Could you use the configuration where the problematic optimization has been disabled? I've sent a pull request.

**Comment by AkihisaYamada** [comment]
@nilslommen Thanks a lot! The bugfix was in time, but if the problem remains we apply the -10 penalty. Stay tuned!
