### ISSUE TITLE
Conflict in C Integer

### ISSUE THREAD

**Issue by AkihisaYamada** [TermCOMP/starexec-master#77]
https://termcomp.herokuapp.com/Y2023/C_Integer.html?filter0=Stroeder_15/ChawdharyCookGulwaniSagivYang-ESOP2008-aaron12_true-termination.c

**Comment by AkihisaYamada** [comment]
@nilslommen @juergengiesl @hiroshi-unno

**Comment by nilslommen** [comment]
I think its the same as https://github.com/TermCOMP/starexec-master/issues/73.

**Comment by hiroshi-unno** [comment]
Thank you.  Yes, this instance does terminate, and it appears that the used configuration of MuVal-RL has the same issue as #73.
